name             'cd-base'
maintainer       'Shawn bower'
maintainer_email 'shawn.bower@gmail.com'
license          'All rights reserved'
description      'Installs/Configures cs-base'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.2.0'
depends          'aws'
depends          'docker'
gem              'aws-sdk-core'
gem              'cucloud'