name              'cd-odsee'
maintainer        'Paul Allen'
maintainer_email  'pea1@cornell.edu'
license           'All rights reserved'
description       'Install Oracle Directory Server Enterprise Edition'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version           '0.1.0'
depends           'aws'
depends           'java'
depends           'tomcat'
depends           'route53'
gem               'aws-sdk-core'
gem               'cucloud'
